name: test
on: [push]
jobs:
  test-example:
    runs-on: ubuntu-latest
    steps:
      - name: Donwload repository
        uses: actions/checkout@v2
      - name: Build LaTex document
        uses: antaljanosbenjamin/compile-latex@v1.0.0
        with:
          file: main.tex
          args: -pdf
      - run: '(test -f main.pdf && echo PDF exists) || (echo PDF does not exist && exit 1)'
      - name: Copy
        run: |
          mkdir out
          cp ./main.pdf ./out/main.pdf
      - name: Upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ./out/main.pdf
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: out
          GIT_CONFIG_NAME: MaxiRam
          GIT_CONFIG_EMAIL: maxiramos9@hotmail.com