name: test
on: [push]
jobs:
  test-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Build
      - uses: antaljanosbenjamin/compile-latex@v1.0.0
        with:
          file: main.tex
          args: -pdf
      - run: '(test -f main.pdf && echo PDF exists) || (echo PDF does not exist && exit 1)'